### PR TITLE
Allowed reauthorisation using existing AuthorizationId and Token

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by johnbfair** [comment]
Is there a way to write a test for this or would you have to wait for the token to expire before calling this?

**Comment by JakeGinnivan** [comment]
Sure, the scenario is restarting the app, and not wanting the user to login again. I can stash the authid and token in settings. Rather than getting them to login every time

Not sure if this is the best way, probably doing proper oAuth would be better, but this got me over the line.

It is just a demo app for https://github.com/JakeGinnivan/VSTOContrib/tree/master/src/GitHubForOutlook.Core which IronGitHub seemed the simplest solution to get me up and running.

Thoughts on this approach?

**Comment by johnbfair** [comment]
Depends on how you're storing the tokens, if it's open to the web or an internal corporate network, etc.  Having the token/userid combo stored in something like session means you could run the risk of someone being able to impersonate another user.

**Comment by JakeGinnivan** [comment]
It is just local settings in the roaming profile.

**Comment by timerickson** [comment]
@JakeGinnivan I think you just need to merge a fresh pull on your branch to get the fix for this failing test - it was fixed by @johnbfair.  Then we can merge this in.  I don't have a problem with this change.

**Pull request closed without merging**
