### PR TITLE
Added call to get my repositories

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by johnbfair** [comment]
It looks like something has changed in the URL returned from GitHub: http://ci.johnduhart.me/viewLog.html?buildId=98&buildTypeId=IronGitHub_IronGithubCi

Test(s) failed. Expected string to be 
"https://gist.github.com/raw/6287413/d598c68a9b50654d1242f0e0881728f64d97d85c/file.txt" with a length of 85, but 
"https://gist.github.com/johnduhart/6287413/raw/d598c68a9b50654d1242f0e0881728f64d97d85c/file.txt" has a length of 96.

**Comment by JakeGinnivan** [comment]
I saw that, but was unrelated. Thought id leave it alone

**Comment by johnbfair** [comment]
Yeah, but something we'll have to fix.  The tests themselves (at least) need to be updated to reflect that change.  Could have other side effects as well as (won't know without looking at the code).

**Comment by johnbfair** [comment]
You'll also want to add tests for this guy (as we talked about in another of your PRs).

**Comment by JakeGinnivan** [comment]
Yep. 

Re broken test: Agreed, I had just written all these PR's in my demo project, thought id throw PR's up to at least get a convo started. Will get tests around my stuff tomorrow

**Comment by johnbfair** [comment]
No problem man.  I'll research the broken test on my side this weekend.

**Comment by johnbfair** [comment]
Alright, if you pull latest from master and update these PRs w/ that fix then the tests should pass for this PR.  Then all you have to do is add your new tests and we'll be good. :thumbsup:

**Comment by timerickson** [comment]
Ah, I see @johnbfair already helping you out - sorry for the noise.  Just trying to get plugged back in a bit to get these few changes in to actually do the NuGet package update.  w00t!

**Comment by cmhokej** [comment]
Ok

**Pull request closed without merging**
