### PR TITLE
Added API to get issues of a repo

### PR DESCRIPTION
**Pull request by jessenic**

### CODE REVIEW

**Comment by johnbfair** [comment]
Should there be tests on this before we accept a PR? If not then my code's ready for PR!  :wink:

**Comment by timerickson** [comment]
Yes, I want a test added for this.  @jessenic ???

@johnbfair is this going to hold you up?  I think @jessenic should be able to merge this after you push?  On with the PR!

**Comment by johnbfair** [comment]
@timerickson No I don't think it will hold me up. I've got a ton of other tests to write anyway. :thumbsup: Plus it'll take me a bit to get the MSTest -> NUnit PR merged into my changes so I'm not worried.

**Comment by timerickson** [comment]
@jessenic Can you add a test for this so we can get this merged?

**Comment by jessenic** [comment]
@timerickson Sorry I have been busy, but I'll try to have time tonight.

**Comment by johnduhart** [comment]
Closing as #13 is now merged.

**Pull request closed without merging**
