### PR TITLE
Added api call to create an issue

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by johnbfair** [comment]
You need to add a test for this.

**Comment by JakeGinnivan** [comment]
Is there a set repo which we can do integration tests against? And gathering you are after a integration test rather than a unit test?

**Comment by johnbfair** [comment]
Yes the tests used to run against @in2bitstest but @johnduhart removed the login/password (likely for security reasons).  Each of us just make a testaccount.json file that has the login/password (and is prevented from accidental checkin by the .gitignore file) for the individual developer's test user.  

And you are correct, almost all of the tests for this repo are integration tests.

**Comment by JakeGinnivan** [comment]
ok cool, so if I write a test the build server has credentials all setup in testaccount.json and it should just work?

Will write tests tomorrow morning

**Comment by johnbfair** [comment]
Correct. 

You'll also probably want to create the ability to close an issue as well.  I assume there's an API endpoint that allows you to close issues.  That way your integration test can create the issue and close the issue (try to clean up after yourself as best you can).  These integration tests get run a LOT so if you're making an issue (w/o closing it) that will get messy.

**Comment by JakeGinnivan** [comment]
Yeah fair point, will do

**Comment by JakeGinnivan** [comment]
FYI looks like a build is hanging

http://ci.johnduhart.me/viewLog.html?buildId=101&tab=buildResultsDiv&buildTypeId=IronGitHub_IronGithubCi

**Comment by johnbfair** [comment]
Yeah, maybe @johnduhart can fix that.

**Comment by timerickson** [comment]
I think you just need to merge in a fresh pull on this to get @johnbfair 's fix for the failing test, and we can get this merged in.

**Pull request closed without merging**
